version: 2.1

executors:
  docker:
    docker:
      - image: circleci/python:3.6
        user: root

workflows:
  test:
    jobs:
      - docker-publish/publish:
          name: build
          deploy: false
          dockerfile: .circleci/Dockerfile
          executor: docker
          image: test/test
          path: .circleci
