description: Builds and Tags a Docker Image.

parameters:
  dockerfile:
    description: Name of dockerfile to use. Defaults to Dockerfile.
    type: string
    default: Dockerfile
  path:
    description: Path to the directory containing your Dockerfile and build context. Defaults to . (working directory).
    type: string
    default: .
  image:
    description: Name of image to create. Defaults to a combination of $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME.
    type: string
    default: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
  tag:
    description: Value for tag to use. Defaults to $CIRCLE_SHA1.
    type: string
    default: $CIRCLE_SHA1
  registry:
    description: Name of registry to use. Defaults to docker.io.
    type: string
    default: docker.io
  extra_build_args:
    description: >
      Extra flags to pass to docker build. For examples, see
      https://docs.docker.com/engine/reference/commandline/build
    type: string
    default: ""
  label_prefix:
    description: Prefix for Docker labels applied to the image. Defaults to $CIRCLE_PROJECT_USERNAME.
    type: string
    default: $CIRCLE_PROJECT_USERNAME

steps:
  - run:
      name: Build Docker Image
      command: |
        docker build \
          -t << parameters.registry >>/<< parameters.image >>:${CIRCLE_SHA1} \
          -t << parameters.registry >>/<< parameters.image >>:${CIRCLE_SHA1:0:7} \
          --label "<< parameters.label_prefix >>.build-system=circleci" \
          --label "<< parameters.label_prefix >>.circleci.build-number=${CIRCLE_BUILD_NUM}" \
          --label "<< parameters.label_prefix >>.circleci.build-timestamp=$(date -uIs)" \
          --label "<< parameters.label_prefix >>.circleci.build-url=${CIRCLE_BUILD_URL}" \
          --label "<< parameters.label_prefix >>.circleci.git-branch=${CIRCLE_BRANCH}" \
          --label "<< parameters.label_prefix >>.circleci.git-commit=${CIRCLE_SHA1}" \
          --label "<< parameters.label_prefix >>.circleci.git-repo-url=${CIRCLE_REPOSITORY_URL}" \
          --label "<< parameters.label_prefix >>.circleci.workflow-id=${CIRCLE_WORKFLOW_ID}" \
          <<#parameters.extra_build_args>><<parameters.extra_build_args>><</parameters.extra_build_args>> \
          -f << parameters.dockerfile >> -t \
          << parameters.registry >>/<< parameters.image >>:<< parameters.tag >> \
          << parameters.path >>
